In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: agg

In [95]:
dataset = pd.read_csv("/content/bill_authentication.csv")
dataset

      Variance  Skewness  Curtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [96]:
dataset.shape

(1372, 5)

In [97]:
dataset.head()

   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [98]:
X = dataset.drop('Class', axis = 1)
Y = dataset['Class']

In [99]:
X

      Variance  Skewness  Curtosis  Entropy
0      3.62160   8.66610   -2.8073 -0.44699
1      4.54590   8.16740   -2.4586 -1.46210
2      3.86600  -2.63830    1.9242  0.10645
3      3.45660   9.52280   -4.0112 -3.59440
4      0.32924  -4.45520    4.5718 -0.98880
...        ...       ...       ...      ...
1367   0.40614   1.34920   -1.4501 -0.55949
1368  -1.38870  -4.87730    6.4774  0.34179
1369  -3.75030 -13.45860   17.5932 -2.77710
1370  -3.56370  -8.38270   12.3930 -1.28230
1371  -2.54190  -0.65804    2.6842  1.19520

[1372 rows x 4 columns]

In [100]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: Class, Length: 1372, dtype: int64

In [101]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=21)

In [102]:
X_train

      Variance  Skewness  Curtosis  Entropy
1198  -1.78860   -6.3486  5.615400  0.42584
714    2.55590    3.3605  2.032100  0.26809
556    1.56730    7.9274 -0.056842 -2.16940
471    0.39559    6.8866  1.058800 -0.67587
1106  -0.12690   -1.1505 -0.951380  0.57843
...        ...       ...       ...      ...
368    3.49850    3.1639  0.226770 -0.16510
48     3.91020    6.0650 -2.453400 -0.68234
772   -2.41150   -9.1359  9.344400 -0.65259
1231  -0.77848    3.4019 -3.485900 -3.55690
969   -2.17860   -6.4479  6.034400 -0.20777

[1097 rows x 4 columns]

In [103]:
X_test

      Variance  Skewness  Curtosis   Entropy
1148 -0.266540  -0.64562  -0.42014  0.891360
875  -1.862900  -0.84841   2.53770  0.097399
631   1.899400   0.97462   4.22650  0.813770
1166 -2.197900  -2.12520   1.71510  0.451710
337   1.019100   2.33000   4.93340  0.829290
...        ...       ...       ...       ...
802   0.600500   1.93270  -3.28880 -0.324150
1001 -0.036127   1.52500  -1.40890 -0.761210
227  -2.647900  10.13740  -1.33100 -5.470700
842  -1.896900  -6.78930   5.27610 -0.325440
1036 -2.389800  -0.78427   3.01410  0.762050

[275 rows x 4 columns]

In [104]:
Y_train

1198    1
714     0
556     0
471     0
1106    1
       ..
368     0
48      0
772     1
1231    1
969     1
Name: Class, Length: 1097, dtype: int64

In [105]:
Y_test

1148    1
875     1
631     0
1166    1
337     0
       ..
802     1
1001    1
227     0
842     1
1036    1
Name: Class, Length: 275, dtype: int64

In [106]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, Y_train)

DecisionTreeClassifier()

In [107]:
print(classifier.min_weight_fraction_leaf)
print(classifier.get_depth)
print(classifier.get_depth())
print(classifier.get_n_leaves)
print(classifier.get_n_leaves())
print(classifier.score)
print(classifier.score(X_train, Y_train))
print(classifier.score(X_test, Y_test))

0.0
<bound method BaseDecisionTree.get_depth of DecisionTreeClassifier()>
7
<bound method BaseDecisionTree.get_n_leaves of DecisionTreeClassifier()>
23
<bound method ClassifierMixin.score of DecisionTreeClassifier()>
1.0
0.9709090909090909

In [108]:
Y_pred = classifier.predict(X_test)

In [109]:
Y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1])

In [110]:
print(Y_pred)

[1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 1 0 0 1 1 1 0 1
 1 1 0 0 0 0 0 1 0 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 1 1 0
 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0
 1 0 1 1 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 0
 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 0 0 0 1
 0 0 0 1 0 1 1 1 1 0 0 1 0 0 1 1 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1
 0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1
 0 1 1 0 0 1 0 0 0 1 1 1 1 0 1 1]

In [111]:
from sklearn.metrics import classification_report, confusion_matrix, plot_confusion_matrix, ConfusionMatrixDisplay
print(confusion_matrix)
print(classification_report)

<function confusion_matrix at 0x7fd7a5bd2680>
<function classification_report at 0x7fd7a5bd2ef0>

In [112]:
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[147   6]
 [  2 120]]
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       153
           1       0.95      0.98      0.97       122

    accuracy                           0.97       275
   macro avg       0.97      0.97      0.97       275
weighted avg       0.97      0.97      0.97       275

In [113]:
confusion_matrix(Y_test, Y_pred)

array([[147,   6],
       [  2, 120]])

In [114]:
classification_report(Y_test, Y_pred)

'              precision    recall  f1-score   support\n\n           0       0.99      0.96      0.97       153\n           1       0.95      0.98      0.97       122\n\n    accuracy                           0.97       275\n   macro avg       0.97      0.97      0.97       275\nweighted avg       0.97      0.97      0.97       275\n'

In [115]:
plot_confusion_matrix

<function sklearn.metrics._plot.confusion_matrix.plot_confusion_matrix(estimator, X, y_true, *, labels=None, sample_weight=None, normalize=None, display_labels=None, include_values=True, xticks_rotation='horizontal', values_format=None, cmap='viridis', ax=None, colorbar=True)>

In [116]:
print(plot_confusion_matrix)

<function plot_confusion_matrix at 0x7fd7a5ab2f80>

In [118]:
ConfusionMatrixDisplay(Y_test, Y_pred,)

TypeError: ignored

In [119]:
# Activity:
df = pd.read_csv("/content/PastHires.csv")

In [120]:
df

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned,Hired
0,10,Y,4,BS,N,N,Y
1,0,N,0,BS,Y,Y,Y
2,7,N,6,BS,N,N,N
3,2,Y,1,MS,Y,N,Y
4,20,N,2,PhD,Y,N,N
5,0,N,0,PhD,Y,Y,Y
6,5,Y,2,MS,N,Y,Y
7,3,N,1,BS,N,Y,Y
8,15,Y,5,BS,N,N,Y
9,0,N,0,BS,N,N,N
10,1,N,1,PhD,Y,N,N
11,4,Y,1,BS,N,Y,Y
12,0,N,0,PhD,Y,N,Y

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Years Experience    13 non-null     int64
 1   Employed?           13 non-null     object
 2   Previous employers  13 non-null     int64
 3   Level of Education  13 non-null     object
 4   Top-tier school     13 non-null     object
 5   Interned            13 non-null     object
 6   Hired               13 non-null     object
dtypes: int64(2), object(5)
memory usage: 856.0+ bytes

In [123]:
# Decision tree:
from sklearn.tree import DecisionTreeClassifier

In [124]:
X = df.drop('Hired', axis = 1)
Y = df['Hired']
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

In [125]:
X

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned
0,10,Y,4,BS,N,N
1,0,N,0,BS,Y,Y
2,7,N,6,BS,N,N
3,2,Y,1,MS,Y,N
4,20,N,2,PhD,Y,N
5,0,N,0,PhD,Y,Y
6,5,Y,2,MS,N,Y
7,3,N,1,BS,N,Y
8,15,Y,5,BS,N,N
9,0,N,0,BS,N,N
10,1,N,1,PhD,Y,N
11,4,Y,1,BS,N,Y
12,0,N,0,PhD,Y,N

In [126]:
Y

0     Y
1     Y
2     N
3     Y
4     N
5     Y
6     Y
7     Y
8     Y
9     N
10    N
11    Y
12    Y
Name: Hired, dtype: object

In [127]:
# Using map function
Y = Y.map({'Y': 1, 'N': 0})

In [128]:
Y

0     1
1     1
2     0
3     1
4     0
5     1
6     1
7     1
8     1
9     0
10    0
11    1
12    1
Name: Hired, dtype: int64

In [129]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

In [131]:
classifier = DecisionTreeClassifier
classifier.fit(X_train, Y_train)

TypeError: ignored

In [133]:
# Solution from Lecturer:
# Activity Solution
import numpy as np
import pandas as pd
from sklearn import tree

input_file = "/content/PastHires.csv"
df = pd.read_csv(input_file, header = 0)

In [134]:
df.head()

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned,Hired
0,10,Y,4,BS,N,N,Y
1,0,N,0,BS,Y,Y,Y
2,7,N,6,BS,N,N,N
3,2,Y,1,MS,Y,N,Y
4,20,N,2,PhD,Y,N,N

In [135]:
d = {'Y': 1, 'N': 0}
df['Hired'] = df['Hired'].map(d)
df['Employed?'] = df['Employed?'].map(d)
df['Top-tier school'] = df['Top-tier school'].map(d)
df['Interned'] = df['Interned'].map(d)
d = {'BS': 0, 'MS': 1, 'PhD': 2}
df['Level of Education'] = df['Level of Education'].map(d)
df.head()

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned,Hired
0,10,1,4,0,0,0,1
1,0,0,0,0,1,1,1
2,7,0,6,0,0,0,0
3,2,1,1,1,1,0,1
4,20,0,2,2,1,0,0

In [136]:
features = list(df.columns[:6])
features

['Years Experience',
 'Employed?',
 'Previous employers',
 'Level of Education',
 'Top-tier school',
 'Interned']

In [137]:
y = df["Hired"]
X = df[features]

In [138]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X, y)

#Predict employment of an employed 10-year veteran
print (clf.predict([[10, 1, 4, 0, 0, 0]]))
#...and an unemployed 10-year veteran
print (clf.predict([[10, 0, 4, 0, 0, 0]]))

[1]
[0]

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

In [139]:
clf1 = tree.DecisionTreeClassifier()
clf1 = clf1.fit(X,y)
#Predict employment of an employed 10-year veteran
print (clf1.predict([[10, 1, 4, 0, 0, 0]]))
#...and an unemployed 10-year veteran
print (clf1.predict([[10, 0, 4, 0, 0, 0]]))

[1]
[0]

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"

In [140]:
from sklearn.naive_bayes import GaussianNB

clf2 = GaussianNB()
clf2 = clf2.fit(X,y)
#Predict employment of an employed 10-year veteran
print (clf2.predict([[10, 1, 4, 0, 0, 0]]))
#...and an unemployed 10-year veteran
print (clf2.predict([[10, 0, 4, 0, 0, 0]]))

[1]
[0]

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"

In [141]:
## Tutorial 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
dataset = pd.read_csv("/content/bill_authentication.csv")
dataset.shape
dataset.head()
X = dataset.drop('Class', axis=1)
y = dataset['Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[155   2]
 [  2 116]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       157
           1       0.98      0.98      0.98       118

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

In [142]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import BaseDecisionTree
from sklearn.tree import ExtraTreeRegressor
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.ensemble import GaussianNB
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import RandomForestClassifier
from sklearn.tree import RandomForestRegressor
from sklearn.naive_bayes import RandomForestClassifier
from sklearn.naive_bayes import RandomForestRegressor

ImportError: ignored

In [144]:
print (clf2.predict([[10, 1, 4, 0, 0, 0]]))
print (clf1.predict([[10, 1, 4, 0, 0, 0]]))
print (clf.predict([[10, 1, 4, 0, 0, 0]]))

[1]
[1]
[1]

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

In [145]:
# After class, at home Activity:
# Decision tree is slides 2, NB Classifier is slides 1. Random Forest is slides 3.6.
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
tree.DecisionTreeClassifier()
from sklearn.naive_bayes import GaussianNB
GaussianNB()

GaussianNB()

In [146]:
tree.DecisionTreeClassifier()

DecisionTreeClassifier()

In [147]:
RandomForestClassifier(n_estimators=10)

RandomForestClassifier(n_estimators=10)

In [148]:
RandomForestClassifier()

RandomForestClassifier()

In [149]:
# my experiment:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
dataset = pd.read_csv("/content/bill_authentication.csv")
dataset.shape
dataset.head()
X = dataset.drop('Class', axis=1)
y = dataset['Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
##############################################
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X, y)
print(clf)

[[154   2]
 [  0 119]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       156
           1       0.98      1.00      0.99       119

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

RandomForestClassifier(n_estimators=10)

In [150]:
clf1 = tree.DecisionTreeClassifier()
clf1 = clf1.fit(X,y)
print(clf1)
################################################
from sklearn.naive_bayes import GaussianNB
clf2 = GaussianNB()
clf2 = clf2.fit(X,y)
print(clf2)

DecisionTreeClassifier()
GaussianNB()

In [151]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X, y)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[154   2]
 [  0 119]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       156
           1       0.98      1.00      0.99       119

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

In [156]:
y_pred = classifier.predict(X_test)
from sklearn.naive_bayes import GaussianNB
clf2 = GaussianNB()
clf2 = clf2.fit(X,y)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[154   2]
 [  0 119]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       156
           1       0.98      1.00      0.99       119

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

Clarification: Example code is DECISION TREE CLASSIFIER and activity ask for same plus 2 new: NAIVE BAYES and RANDOM FOREST.

In [ ]:
# END